---

- hosts: TEST
  become: true
  pre_tasks:

  - name: update repository index
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Debian"

- hosts: TEST
  become: true
  roles:
    - base
    - secure

- hosts: TEST
  roles:
    - basic
