---

- hosts: DOMO
  become: true
  pre_tasks:

  - name: update repository index
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Debian"

- hosts: DOMO
  become: true
  roles:
#    - base
#    - secure
    - fail2ban

- hosts: TEST
  roles:
#    - basic
