- name: Create Directory structure with permission
  file:

    path: "{{ tree_path }}/{{ item }}"
    mode: "0755"
    state: directory
  with_items: "{{ Dir_name }}"

- name: Copy baschrc
  copy:
    src: ~/ansible/Project_1/roles/base/files/.bashrc
    dest: ~/.bashrc
    backup: yes
  register: rc

- name: run source function
  shell: . ~/.bashrc
  register: func_result
  when: rc.changed

- name: check result
  debug:
    var: func_result.stdout
  when: rc.changed
