# Last update : 16-11-2022
# install fail2ban
# copy jail naar jail.local
# edit file for ssh protocol
# edit file foor ignore ip 127.0.0.1 / 10.0.0.0 / 172. / 192.168.1.0
# State: present zorgt ervoor dat systeem aanwezigheid gaat checken; uitzetten om opnieuw port = ssh te kunnen opvoeren.
---
- hosts: TEST
  become: yes
  tasks:
    - name: Install fail2ban.
      apt:
        name: fail2ban
        state: latest
        update-cache: yes
    - name: copy src to dest
      copy:
        src: /etc/fail2ban/jail.conf
        dest: /etc/fail2ban/jail.bak
    - name: Insert lines end of file.
      lineinfile:
        path: /etc/fail2ban/jail.bak
        state: present
        insertafter: EOF
        line: " {{ item }} "
      with_items:
        - "[ssh]"
        - enable  = true
        - port    = ssh
        - filter  = sshd
        - "logpath = /var/log/auth.log"
        - maxretry= 3
        - bantime = -1
    - name: add ip adresses to ignore ip
      tags: example1
      lineinfile:
        path: /etc/fail2ban/jail.bak
        regexp: "#ignoreip = *"
        line: "ignoreip = 127.0.0.1/8,192.168.1.0/24,10.6.0.0/16"
        state: present
      register: example1out
    - name: restart service fail2ban
      service:
        name: fail2ban
        state: restarted 
