- name : add ssh key for ansible
  authorized_key:
    user: ansible
    key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOJY7+v8Un9/DE9eRJxczPaW5FVLkQFaYxCwQwYa7QKD LINUX 

- name : install packages
  apt:
    name: 
      - nano
      - ufw
      - fail2ban
      - apticron
      - logwatch
      - unattended-upgrades
      - apt-listchanges
    state: latest

